version: '3'
services:
  database.pdisc.local:
    container_name: pdisc-database
    image: wangxian/alpine-mysql
    volumes:
      - ./data/database:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - ./config/database.env

  api.pdisc.local:
    container_name: pdisc-api
    build:
     context: ./apps/api
    volumes:
      - ./apps/api:/app
    ports:
      - "3000:3000"
    env_file:
      - ./config/api.env
    links:
      - database.pdisc.local